# Generated by Django 5.2 on 2025-06-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_rename_lead_client_converted_from_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
