# Generated by Django 5.2 on 2025-06-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_alter_client_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
