# Generated by Django 5.2 on 2025-05-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="end_time",
            new_name="start",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_time",
        ),
        migrations.AddField(
            model_name="event",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
