# Generated by Django 5.2 on 2025-05-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
        ("lead", "0001_initial"),
        ("task", "0002_taskcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_client",
                to="client.client",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_lead",
                to="lead.lead",
            ),
        ),
    ]
