# Generated by Django 5.2 on 2025-06-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_alter_task_priority_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
