# Generated by Django 5.2 on 2025-06-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0005_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "Open"),
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="-",
                max_length=20,
                null=True,
            ),
        ),
    ]
