# Generated by Django 5.2 on 2025-07-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0007_task_due_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
