# Generated by Django 5.2 on 2025-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0009_alter_task_due_date_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
