# Generated by Django 5.2 on 2025-07-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0010_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                ],
                default="-",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="",
                max_length=20,
                null=True,
            ),
        ),
    ]
