# Generated by Django 5.2 on 2025-05-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("contacted", "Contacted"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                ],
                default="----",
                max_length=255,
            ),
        ),
    ]
