# Generated by Django 5.2 on 2025-06-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0002_alter_lead_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
