# Generated by Django 5.2 on 2025-07-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0003_alter_lead_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
